In [1]:
import numpy as np

In [2]:
import time


In [3]:
import sys

In [15]:
size=100000000

In [16]:
l1 = range(size)

In [17]:
l2 = range(size)

In [18]:
a1 = np.arange(size)

In [19]:
a2 = np.arange(size)

In [20]:
#python list

start = time.time()
result = [(x+y) for x,y in zip(l1, l2)]
print('python took time:', time.time() - start)

python took time: 75.01630520820618


In [21]:
# numpy list
start = time.time()
result = a1+a2
print('numpy took time:', time.time() - start)

MemoryError: 

In [1]:
b = [1,2,3]

In [2]:
b?


In [3]:
a= np.random.randn(100,100)

NameError: name 'np' is not defined

In [4]:
import numpy as np


In [6]:
a = np.random.randn(100,100)

In [7]:
%timeit np.dot(a,a)

40.5 µs ± 935 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
x = [5,1,8,3,2]

In [10]:
pivot = x[0]
c = []
for item in x:
    if item<pivot:
        less.append(c)
    else:
        continue

NameError: name 'less' is not defined

In [11]:
a = 4.54
b=3
print('a is {} and b is {}'.format(type(a), type(b)))

a is <class 'float'> and b is <class 'int'>


In [12]:
a/b

1.5133333333333334

In [13]:
a = 5
a.isinstance(int)

AttributeError: 'int' object has no attribute 'isinstance'

In [15]:
isinstance(a, int)

True

In [17]:
a=4.5
isinstance(a, (int, float))

True

In [59]:
f =open("temp.py",'r+')

In [52]:
f.write("hello")

5

In [60]:
next(f)

'hello\n'

In [61]:
f.__seek__0)
f.readline()

'hello\n'

In [65]:
dir(f)

['_CHUNK_SIZE',
 '__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_checkClosed',
 '_checkReadable',
 '_checkSeekable',
 '_checkWritable',
 '_finalizing',
 'buffer',
 'close',
 'closed',
 'detach',
 'encoding',
 'errors',
 'fileno',
 'flush',
 'isatty',
 'line_buffering',
 'mode',
 'name',
 'newlines',
 'read',
 'readable',
 'readline',
 'readlines',
 'reconfigure',
 'seek',
 'seekable',
 'tell',
 'truncate',
 'writable',
 'write',
 'write_through',
 'writelines']

In [66]:
f.flush()

In [67]:
f.read()

''

In [68]:
f.seek(0)

0

In [69]:
f.read()

'hello\nhello\n'

In [70]:
f.

SyntaxError: invalid syntax (<ipython-input-70-ecbd3b12d2e2>, line 1)

In [71]:
f.__del__

<method-wrapper '__del__' of _io.TextIOWrapper object at 0x7fb6f1cc2dc8>

In [72]:
f.read()

''

In [73]:
f.seek(0)

0

In [74]:
f.read()

'hello\nhello\n'

In [75]:
f.truncate(0)

0

In [76]:
f.seek(0)

0

In [77]:
f.read()

''

In [78]:
val = 'espanol'

In [79]:
type(val)

str

In [80]:
s = '3.14'

In [81]:
val = float(s)

In [82]:
val

3.14

In [83]:
s

'3.14'

In [84]:
type(val)

float

In [85]:
a=5
if a==5 :
    print('it's positive')
else:
    print('it's negative')

SyntaxError: invalid syntax (<ipython-input-85-56be0256d2d0>, line 3)

In [86]:
seq = [1,2,None, 4, None, 5]

In [88]:
total = 0
for i in seq:
    if i is None:
        continue
    total+=i

In [89]:
total

12

In [91]:
tup = tuple('str')

In [92]:
tup

('s', 't', 'r')

In [93]:
tup = tuple(['foo', [1,2], True])

In [94]:
tup

('foo', [1, 2], True)

In [95]:
tup[2] = False

TypeError: 'tuple' object does not support item assignment

In [96]:
tup[1].append(3)

In [97]:
tup

('foo', [1, 2, 3], True)

In [98]:
a,b =1,2

In [99]:
a

1

In [100]:
b

2

In [101]:
b,a = a,b

In [102]:
a

2

In [103]:
b

1

In [104]:
seq = [(1,2,3), (4,5,6), (7,8,9)]

In [105]:
for a, b, c in seq:
    print('a={}, b={}, c={}'.format(a,b,c))

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [106]:
val = 1,2,3,4

In [107]:
val

(1, 2, 3, 4)

In [108]:
a, b, *_ = val

In [109]:
a

1

In [110]:
a,b

(1, 2)

In [111]:
a,b,*_

(1, 2, 3, 4)

In [112]:
*_

SyntaxError: can't use starred expression here (<ipython-input-112-2de828294d4c>, line 4)

In [113]:
!ls

'Chapter 4.ipynb'	      My_Best_Codes.ipynb   temp.py
'Chapter 5.ipynb'	      newfile.txt	   'Variable Scope.ipynb'
'Loops and Functions.ipynb'   Numpy.ipynb


In [114]:
!pwd

/home/icpl11549/anaconda3/my_codes


In [115]:
!ls

'Chapter 4.ipynb'	      My_Best_Codes.ipynb   temp.py
'Chapter 5.ipynb'	      newfile.txt	   'Variable Scope.ipynb'
'Loops and Functions.ipynb'   Numpy.ipynb


In [116]:
!cd anconda3

/bin/sh: 1: cd: can't cd to anconda3


In [118]:
data = np.random.randn(2,3)

In [119]:
data


array([[-0.01744631, -0.89299842, -0.45078806],
       [-0.46227224, -0.50896751,  0.02207422]])

In [121]:
data*100

array([[ -1.74463107, -89.29984192, -45.07880623],
       [-46.22722441, -50.89675138,   2.20742241]])

In [122]:
data +  data

array([[-0.03489262, -1.78599684, -0.90157612],
       [-0.92454449, -1.01793503,  0.04414845]])

In [123]:
data

array([[-0.01744631, -0.89299842, -0.45078806],
       [-0.46227224, -0.50896751,  0.02207422]])

In [124]:
data.shape()

TypeError: 'tuple' object is not callable

In [125]:
data.shape


(2, 3)

In [126]:
data.dtype


dtype('float64')

In [127]:
data = [6, 7.5, 0, 8, 1]

In [128]:
arr1 = np.array(data)

In [129]:
arr1

array([6. , 7.5, 0. , 8. , 1. ])

In [130]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [131]:
arr2 = np.array(data2)

In [132]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [133]:
arr2.ndim


2

In [134]:
arr2.shape

(2, 4)

In [135]:
arr1.dtype

dtype('float64')

In [136]:
arr2.dtype

dtype('int64')

In [137]:
np.empty()?


SyntaxError: invalid syntax (<ipython-input-137-4dbb8b193d41>, line 1)

In [138]:
empty?


Object `empty` not found.


In [139]:
np.empty((2,3,2))

array([[[-5.79751039e-019,  5.02034658e+175],
        [ 5.98926260e-038,  2.64839154e-032],
        [ 5.10524413e-066,  6.56372315e+169]],

       [[ 5.01163109e+217,  5.49419094e-143],
        [ 9.80058441e+252,  1.30304358e-142],
        [ 2.14027814e+161,  2.41083437e+233]]])

In [143]:
np.empty_like()

array(0)

In [144]:
arr1 = np.array([1,2,3], dtype = np.float64)

In [146]:
arr2 = np.array([1,2,3], dtype = np.int32)

In [147]:
arr1

array([1., 2., 3.])

In [148]:
arr2

array([1, 2, 3], dtype=int32)

In [149]:
arr = np.array([1,2,3,4,5])

In [150]:
arr.dtype

dtype('int64')

In [151]:
float_arr = arr.astype(np.float64)

In [152]:
float_arr.dtype

dtype('float64')

In [153]:
arr = np.array([1.2, 3.5, 6.7])

In [154]:
arr.dtype

dtype('float64')

In [155]:
arr.astype(int32)

NameError: name 'int32' is not defined

In [156]:
arr.astype(np.int32)

array([1, 3, 6], dtype=int32)

In [157]:
x = np.random.randn(8)

In [158]:
y = np.random.randn(8)

In [159]:
x

array([-0.9360833 , -0.34970533, -0.33124072,  0.5160439 ,  0.27465593,
        0.64240871,  0.29800683, -1.90031351])

In [160]:
y

array([-0.31600133, -1.06856482,  0.72200677,  2.27455907,  0.88012649,
        1.45183377,  0.68354062, -0.31260874])

In [161]:
np.maximum(x, y)

array([-0.31600133, -0.34970533,  0.72200677,  2.27455907,  0.88012649,
        1.45183377,  0.68354062, -0.31260874])

In [162]:
arr = np.array([[1,2,3], [4,5,6]])

In [163]:
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [165]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [166]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [167]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [168]:
arr2>arr

array([[False, False, False],
       [False, False, False]])

In [169]:
    arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [170]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [171]:
arr2d[0][2]

3

In [172]:
arr2d[0, 2]

3

In [174]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])

In [175]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [1]:
data = np.random.randn(7,4)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
data = np.random.randn(7, 4)

In [4]:
data

array([[-0.11215127, -1.30069802,  0.67252535,  0.04497352],
       [-0.15823653,  0.06997802, -2.39482638,  1.17891919],
       [ 1.30003619,  1.19797653,  1.32330669, -0.08336182],
       [ 0.49359209,  1.35414232, -0.01916676, -1.06865393],
       [-1.10118953, -0.56570633,  0.3839233 , -0.13149579],
       [ 0.43610538,  0.51749295, -0.00395226, -0.5102268 ],
       [ 0.17988812,  0.02747499,  0.20339956, -1.9017704 ]])

In [5]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])

In [8]:
data[names == 'bob']

array([[-0.11215127, -1.30069802,  0.67252535,  0.04497352],
       [ 0.49359209,  1.35414232, -0.01916676, -1.06865393]])

In [9]:
names['bob']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [11]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [12]:
names != 'bob'

array([False,  True,  True, False,  True,  True,  True])

In [13]:
data[~(names == 'bob')]

array([[-0.15823653,  0.06997802, -2.39482638,  1.17891919],
       [ 1.30003619,  1.19797653,  1.32330669, -0.08336182],
       [-1.10118953, -0.56570633,  0.3839233 , -0.13149579],
       [ 0.43610538,  0.51749295, -0.00395226, -0.5102268 ],
       [ 0.17988812,  0.02747499,  0.20339956, -1.9017704 ]])

In [14]:
mask = (names=='bob') | (names=='will')

In [15]:
names[mask]

array(['bob', 'will', 'bob', 'will'], dtype='<U4')

In [16]:
names == mask

/home/icpl11549/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.


False

names == 'mask'

In [17]:
mask

array([ True, False,  True,  True,  True, False, False])

In [18]:
data[mask]

array([[-0.11215127, -1.30069802,  0.67252535,  0.04497352],
       [ 1.30003619,  1.19797653,  1.32330669, -0.08336182],
       [ 0.49359209,  1.35414232, -0.01916676, -1.06865393],
       [-1.10118953, -0.56570633,  0.3839233 , -0.13149579]])

In [19]:
data[data<0] = 0

In [20]:
data

array([[0.        , 0.        , 0.67252535, 0.04497352],
       [0.        , 0.06997802, 0.        , 1.17891919],
       [1.30003619, 1.19797653, 1.32330669, 0.        ],
       [0.49359209, 1.35414232, 0.        , 0.        ],
       [0.        , 0.        , 0.3839233 , 0.        ],
       [0.43610538, 0.51749295, 0.        , 0.        ],
       [0.17988812, 0.02747499, 0.20339956, 0.        ]])

In [21]:
data[names != 'joe'] = 7

In [22]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.06997802, 0.        , 1.17891919],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.43610538, 0.51749295, 0.        , 0.        ],
       [0.17988812, 0.02747499, 0.20339956, 0.        ]])

In [24]:
names != 'joe'

array([ True, False,  True,  True,  True, False, False])

In [26]:
arr = np.empty((8,4))

In [27]:
arr

array([[6.95032023e-310, 6.95033824e-310, 6.95033824e-310,
        6.95033631e-310],
       [6.95033821e-310, 6.95032023e-310, 6.95033824e-310,
        6.95033823e-310],
       [6.32404027e-322, 1.26480805e-321, 4.66924473e-310,
        9.63428009e-322],
       [0.00000000e+000, 0.00000000e+000, 4.53956082e+259,
        5.02034658e+175],
       [4.79335946e+174, 3.38058785e-057, 4.05621789e+174,
        5.78732692e+174],
       [5.01163190e+217, 5.49419094e-143, 9.80058441e+252,
        1.30304358e-142],
       [2.14027814e+161, 2.41083437e+233, 4.26581542e-096,
        9.08366793e+223],
       [1.10769852e-047, 4.75069853e+174, 6.17163167e-042,
        1.74038660e+184]])

In [28]:
for i in range(8):
    arr[i] = i;

In [29]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [32]:
arr[:4, 1:]

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [33]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [34]:
arr = np.arange(32).reshape(8, 4)

In [35]:
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [37]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [38]:
arr = np.arange(15).reshape(3,5)

In [39]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [42]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
arr = np.arange(16).reshape(2,2,4)

In [44]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [45]:
arr = np.arange(10)

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [49]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [50]:
x = np.random.randn(8)

In [51]:
y = np.random.randn(8)

In [52]:
x

array([ 0.62723645,  0.08782439,  1.42693307, -0.1388574 ,  1.92063793,
        0.15497505,  0.62304409,  0.21203705])

In [53]:
y

array([-0.90214859,  0.46501658, -0.70031664,  1.42883418,  0.91230305,
       -0.07214176, -1.23988437,  2.01397706])

In [54]:
np.maximum(x, y)

array([0.62723645, 0.46501658, 1.42693307, 1.42883418, 1.92063793,
       0.15497505, 0.62304409, 2.01397706])

In [55]:
arr = np.random.randn(7)*5

In [56]:
arr

array([ 4.38680064, -0.78859589,  3.50103171,  4.90630966,  9.7459569 ,
        2.29582893,  6.68545683])

In [57]:
remainder, whole_number = np.modf(arr)

In [58]:
remainder

array([ 0.38680064, -0.78859589,  0.50103171,  0.90630966,  0.7459569 ,
        0.29582893,  0.68545683])

In [59]:
whole_number

array([ 4., -0.,  3.,  4.,  9.,  2.,  6.])

In [60]:
np.ceil(arr)

array([ 5., -0.,  4.,  5., 10.,  3.,  7.])

In [61]:
arr

array([ 4.38680064, -0.78859589,  3.50103171,  4.90630966,  9.7459569 ,
        2.29582893,  6.68545683])

In [62]:
np.ceil(arr)

array([ 5., -0.,  4.,  5., 10.,  3.,  7.])

In [63]:
np.floor(arr)

array([ 4., -1.,  3.,  4.,  9.,  2.,  6.])

In [64]:
np.sqrt(arr)

/home/icpl11549/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.09446906,        nan, 1.87110441, 2.21501911, 3.12185152,
       1.5151993 , 2.58562504])

In [65]:
points = np.arange(-5, 5, 0.01)

In [66]:
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [67]:
xs, ys = np.meshgrid(points, points)

In [68]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [69]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [74]:
xs, ys = np.meshgrid([1,2,3, 4],[1,2,3])

In [75]:
xs

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [76]:
ys

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [78]:
np.sqrt(xs**2 + ys**2)

array([[1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [3.16227766, 3.60555128, 4.24264069, 5.        ]])

In [80]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [81]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [83]:
cond = np.array([True, False, True, True, False])

In [84]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

In [85]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [87]:
res = np.where(cond, xarr, yarr)

In [88]:
res

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [93]:
arr = np.random.randn(4, 4)

In [94]:
arr

array([[-0.94388759, -1.0086347 , -0.95128514, -0.23160973],
       [ 1.75924731, -2.26216053, -2.32799757, -0.17197737],
       [-0.05519371, -0.08024778,  0.22109328, -1.28617237],
       [-0.3322672 ,  0.08691758, -1.61553722,  0.410601  ]])

In [95]:
arr>0

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False,  True, False],
       [False,  True, False,  True]])

In [96]:
result = np.where(arr>0, 2, -2)

In [97]:
result

array([[-2, -2, -2, -2],
       [ 2, -2, -2, -2],
       [-2, -2,  2, -2],
       [-2,  2, -2,  2]])

In [98]:
arr.ceil()

AttributeError: 'numpy.ndarray' object has no attribute 'ceil'

In [99]:
np.mean(arr)

-0.5493194837872546

In [100]:
np.sum(arr)

-8.789111740596073

In [101]:
arr.sum()

-8.789111740596073

In [103]:
arr.SUM(axis=1)

AttributeError: 'numpy.ndarray' object has no attribute 'SUM'

In [105]:
np.sum(arr(axis=1))

TypeError: 'numpy.ndarray' object is not callable

In [106]:
arr = np.random.randn(100)

In [107]:
np.sum(arr>0)

49

In [108]:
bools = np.array([False, False, True, False])

In [109]:
bools.any()

True

In [110]:
bools.all()

False

In [111]:
arr = np.array([1,2,3,4])

In [112]:
np.save('first_array', arr)

In [113]:
np.load('first_array.npy')

array([1, 2, 3, 4])

In [114]:
!ls

'Chapter 4.ipynb'  'Loops and Functions.ipynb'	 Numpy.ipynb
'Chapter 5.ipynb'   My_Best_Codes.ipynb		 temp.py
 first_array.npy    newfile.txt			'Variable Scope.ipynb'


In [115]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [116]:
y = np.array([[6., 23.], [-1., 7], [8, 9]])

In [117]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [118]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [119]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [120]:
y.dot(x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [121]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [122]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [123]:
np.ones(3)

array([1., 1., 1.])

In [1]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [4]:
y = np.array([[6., 23.], [-1, 7.], [8., 9.]])

In [5]:
x*y

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [6]:
x.shape

(2, 3)

In [7]:
y.shape

(3, 2)

In [8]:
x.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [9]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [17]:
z = np.ones(4)

In [18]:
z

array([1., 1., 1., 1.])

In [19]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [20]:
from numpy.linalg import inv, qr

In [21]:
X = np.random.randn(5, 5)

In [22]:
X

array([[-0.44593641,  0.89181533,  0.07989653, -1.45760694, -0.56200445],
       [ 0.09475928,  0.2157857 ,  0.1746122 ,  0.38857075,  1.75339291],
       [ 1.06200161, -1.82021733,  0.16304357, -1.44895253,  0.83148011],
       [ 0.38953836,  1.12868377, -0.40702046, -0.18598439, -0.69263015],
       [-0.00368221,  0.1498941 , -0.94053239,  0.76612924,  0.60539295]])

In [23]:
mat = np.dot(X.T, X)

In [24]:
mat

array([[ 1.48743971e+00, -1.87120527e+00, -1.01696518e-03,
        -9.27238332e-01,  1.02776651e+00],
       [-1.87120527e+00,  5.45148448e+00, -7.88220598e-01,
         1.32626099e+00, -2.32733715e+00],
       [-1.01696518e-03, -7.88220598e-01,  1.11372291e+00,
        -9.29720845e-01,  1.09352031e-01],
       [-9.27238332e-01,  1.32626099e+00, -9.29720845e-01,
         4.99661287e+00,  8.88351199e-01],
       [ 1.02776651e+00, -2.32733715e+00,  1.09352031e-01,
         8.88351199e-01,  4.92783204e+00]])

In [25]:
inv(mat)

array([[ 1.61005715,  0.49254915,  0.63138867,  0.31650712, -0.17424457],
       [ 0.49254915,  0.4320209 ,  0.31295837,  0.01878923,  0.09097686],
       [ 0.63138867,  0.31295837,  1.37979714,  0.30313214, -0.06914438],
       [ 0.31650712,  0.01878923,  0.30313214,  0.33229223, -0.12376779],
       [-0.17424457,  0.09097686, -0.06914438, -0.12376779,  0.30608326]])

In [26]:
samples = np.random.normal(size= (4,4))

In [27]:
samples

array([[ 0.0691338 , -0.37140455, -1.24543968, -0.0279272 ],
       [-0.78440499, -0.95616962,  0.79775582,  0.19576057],
       [-0.5606612 ,  0.99651467, -0.48888587,  1.12824927],
       [ 0.72457408,  1.56908019,  1.07075127, -0.09360771]])